### ISSUE TITLE
There's more to fix | 이 리팩으로도 안 되는 게 더 있습니다

### ISSUE THREAD

**Issue by HotoRas** [1023megabytes/pack-KoreanFontFix#1]
제가 방금 작업 마친 [MC-254506(JIRA, 영문)](https://bugs.mojang.com/browse/MC-254506)에 보시면, 무려 **1.12.2**의 텍팩을 까서 추려낸 전체 바리에이션을 보실 수 있는데...
여기에 수정된 것보다는 상대적으로 너무 많아요.
자세한 건 JIRA 가서 보세요. 여기다 올리기엔 귀찮음

**Comment by 1023megabytes** [comment]
쌍자음의 ㅜ-ㅝ 문제를 까먹은 것 같네요.
곧 수정하겠습니다.

**Comment by 1023megabytes** [comment]
수정했습니다.
